feature/4: Add getting different projects versions
exasol/maven-project-version-getter pull request #5
Opened 2021-09-16 13:20 UTC by jakobbraun

Closes #4

2021-09-16 13:25 UTC, kaklakariada requested changes

2021-09-16 13:25 UTC, kaklakariada commented on .github/workflows/ci-build.yml
> +          java-version: 11
```suggestion
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
```

2021-09-16 13:25 UTC, kaklakariada commented on .github/workflows/ci-build.yml
> +          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
```suggestion
```

2021-09-17 06:32 UTC, jakobbraun commented
I created a ticket to update the template: https://github.com/exasol/project-keeper-maven-plugin/issues/180

2021-09-17 06:55 UTC, kaklakariada approved these changes

2021-09-17 06:57 UTC, merged